server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048
  error:
    path: /error

spring:
  application:
    name: CoronaVirus Tracker

  # ===============================
  # = Thymeleaf configurations
  # ===============================
  thymeleaf:
    cache: false

# ===============================
# = DATA URL
# ===============================
virus:
  data:
    url: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv

# ===============================
# = LOGGING
# ===============================
debug: true

logging:
  level:
    net:
      lelyak: debug
